dist: trusty
addons:
  apt:
    packages:
    - dpkg
  chrome: stable

language: node_js
node_js:
- node
script:
- 'set -eo pipefail;
   if [[ "${TRAVIS_PULL_REQUEST}" = "false" ]]; then
     npm run test:travis;
   else
     npm run unit:coveralls;
   fi'
