from connect_to_rds import create_postgres_engine
import sqlalchemy

engine = create_postgres_engine("AWS_PostGIS", "postgres", "DEV")

def generate_table(engine, target_schema:str, target_table:str,mode:str):
    
    schema_query = """
        CREATE SCHEMA IF NOT EXISTS {0};
        GRANT ALL PRIVILEGES ON SCHEMA {0} TO PUBLIC;
    """.format(target_schema)

    drop_table_query = """
        DROP TABLE IF EXISTS {}.{};
    """.format(target_schema, target_table)

    create_table_query = """
        CREATE TABLE IF NOT EXISTS {0}.{1} (
            {2}
        );
        GRANT ALL PRIVILEGES ON {0}.{1} TO PUBLIC;
    """.format(target_schema, target_table, get_table_definition(target_table))

    truncate_table_query = """
        TRUNCATE {}.{};
    """.format(target_schema, target_table)

    engine.execute(schema_query)
    if mode.lower=='replace':
        engine.execute(drop_table_query)
    if mode.lower=='truncate':
        engine.execute(truncate_table_query)
    engine.execute(create_table_query)


def get_table_definition(target_table:str):

    data_model_dict = {
        'vision_zero': """
            OBJECTID VARCHAR NULL
            ,GLOBALID   VARCHAR NULL 
            ,REQUESTID VARCHAR NULL
            ,REQUESTTYPE VARCHAR NULL
            ,REQUESTDATE TIMESTAMP NULL
            ,STATUS VARCHAR NULL
            ,STREETSEGID VARCHAR NULL
            ,COMMENTS VARCHAR NULL
            ,USERTYPE VARCHAR NULL
            ,geometry geometry
            """
        ,'crashes_raw':"""
            OBJECTID VARCHAR NULL
            ,CRIMEID VARCHAR NULL
            ,CCN VARCHAR NULL
            ,REPORTDATE TIMESTAMP NULL
            ,ROUTEID VARCHAR NULL
            ,MEASURE VARCHAR NULL
            ,_OFFSET VARCHAR NULL
            ,STREETSEGID VARCHAR NULL
            ,ROADWAYSEGID VARCHAR NULL
            ,FROMDATE TIMESTAMP NULL
            ,TODATE TIMESTAMP NULL
            ,MARID VARCHAR NULL
            ,ADDRESS VARCHAR NULL
            ,LATITUDE VARCHAR NULL
            ,LONGITUDE VARCHAR NULL
            ,XCOORD VARCHAR NULL
            ,YCOORD VARCHAR NULL
            ,WARD VARCHAR NULL
            ,EVENTID VARCHAR NULL
            ,MAR_ADDRESS VARCHAR NULL
            ,MAR_SCORE VARCHAR NULL
            ,MAJORINJURIES_BICYCLIST INT NULL
            ,MINORINJURIES_BICYCLIST INT NULL
            ,UNKNOWNINJURIES_BICYCLIST INT NULL
            ,FATAL_BICYCLIST INT NULL
            ,MAJORINJURIES_DRIVER INT NULL
            ,MINORINJURIES_DRIVER INT NULL
            ,UNKNOWNINJURIES_DRIVER INT NULL
            ,FATAL_DRIVER INT NULL
            ,MAJORINJURIES_PEDESTRIAN INT NULL
            ,MINORINJURIES_PEDESTRIAN INT NULL
            ,UNKNOWNINJURIES_PEDESTRIAN INT NULL
            ,FATAL_PEDESTRIAN INT NULL
            ,TOTAL_VEHICLES INT NULL
            ,TOTAL_BICYCLES INT NULL
            ,TOTAL_PEDESTRIANS INT NULL
            ,PEDESTRIANSIMPAIRED INT NULL
            ,BICYCLISTSIMPAIRED INT NULL
            ,DRIVERSIMPAIRED INT NULL
            ,TOTAL_TAXIS INT NULL
            ,TOTAL_GOVERNMENT INT NULL
            ,SPEEDING_INVOLVED INT NULL
            ,NEARESTINTROUTEID VARCHAR NULL
            ,NEARESTINTSTREETNAME VARCHAR NULL
            ,OFFINTERSECTION VARCHAR NULL
            ,INTAPPROACHDIRECTION VARCHAR NULL
            ,LOCATIONERROR VARCHAR NULL
            ,LASTUPDATEDATE TIMESTAMP NULL
            ,MPDLATITUDE VARCHAR NULL
            ,MPDLONGITUDE VARCHAR NULL
            ,MPDGEOX VARCHAR NULL
            ,MPDGEOY VARCHAR NULL
            ,BLOCKKEY VARCHAR NULL
            ,SUBBLOCKKEY VARCHAR NULL
            ,FATALPASSENGER INT NULL
            ,MAJORINJURIESPASSENGER INT NULL
            ,MINORINJURIESPASSENGER INT NULL
            ,UNKNOWNINJURIESPASSENGER INT NULL
            ,geometry geometry null
            """
        ,'all311':"""
            OBJECTID VARCHAR NULL
            ,SERVICECODE VARCHAR NULL
            ,SERVICECODEDESCRIPTION VARCHAR NULL
            ,SERVICETYPECODEDESCRIPTION VARCHAR NULL
            ,ORGANIZATIONACRONYM VARCHAR NULL
            ,SERVICECALLCOUNT VARCHAR NULL
            ,ADDDATE VARCHAR NULL
            ,RESOLUTIONDATE TIMESTAMP NULL
            ,SERVICEDUEDATE TIMESTAMP NULL
            ,SERVICEORDERDATE TIMESTAMP NULL
            ,INSPECTIONFLAG VARCHAR NULL
            ,INSPECTIONDATE VARCHAR NULL
            ,INSPECTORNAME VARCHAR NULL
            ,SERVICEORDERSTATUS VARCHAR NULL
            ,STATUS_CODE VARCHAR NULL
            ,SERVICEREQUESTID VARCHAR NULL
            ,PRIORITY VARCHAR NULL
            ,STREETADDRESS VARCHAR NULL
            ,XCOORD VARCHAR NULL
            ,YCOORD VARCHAR NULL
            ,LATITUDE VARCHAR NULL
            ,LONGITUDE VARCHAR NULL
            ,CITY VARCHAR NULL
            ,STATE VARCHAR NULL
            ,ZIPCODE VARCHAR NULL
            ,MARADDRESSREPOSITORYID VARCHAR NULL
            ,WARD VARCHAR NULL
            ,DETAILS VARCHAR NULL
            ,geometry geometry null
        """
        ,'address_points':"""
            OBJECTID_12 VARCHAR NULL
            ,OBJECTID VARCHAR NULL
            ,SITE_ADDRESS_PK VARCHAR NULL
            ,ADDRESS_ID VARCHAR NULL
            ,ROADWAYSEGID VARCHAR NULL
            ,STATUS VARCHAR NULL
            ,SSL VARCHAR NULL
            ,TYPE_ VARCHAR NULL
            ,ENTRANCETYPE VARCHAR NULL
            ,ADDRNUM VARCHAR NULL
            ,ADDRNUMSUFFIX VARCHAR NULL
            ,STNAME VARCHAR NULL
            ,STREET_TYPE VARCHAR NULL
            ,QUADRANT VARCHAR NULL
            ,CITY VARCHAR NULL
            ,STATE VARCHAR NULL
            ,FULLADDRESS VARCHAR NULL
            ,SQUARE VARCHAR NULL
            ,SUFFIX VARCHAR NULL
            ,LOT VARCHAR NULL
            ,NATIONALGRID VARCHAR NULL
            ,ZIPCODE4 VARCHAR NULL
            ,XCOORD VARCHAR NULL
            ,YCOORD VARCHAR NULL
            ,STATUS_ID VARCHAR NULL
            ,METADATA_ID VARCHAR NULL
            ,OBJECTID_1 VARCHAR NULL
            ,ASSESSMENT_NBHD VARCHAR NULL
            ,ASSESSMENT_SUBNBHD VARCHAR NULL
            ,CFSA_NAME VARCHAR NULL
            ,HOTSPOT VARCHAR NULL
            ,CLUSTER_ VARCHAR NULL
            ,POLDIST VARCHAR NULL
            ,ROC VARCHAR NULL
            ,PSA VARCHAR NULL
            ,SMD VARCHAR NULL
            ,CENSUS_TRACT VARCHAR NULL
            ,VOTE_PRCNCT VARCHAR NULL
            ,WARD VARCHAR NULL
            ,ZIPCODE VARCHAR NULL
            ,ANC VARCHAR NULL
            ,NEWCOMMSELECT06 VARCHAR NULL
            ,NEWCOMMCANDIDATE VARCHAR NULL
            ,CENSUS_BLOCK VARCHAR NULL
            ,CENSUS_BLOCKGROUP VARCHAR NULL
            ,FOCUS_IMPROVEMENT_AREA VARCHAR NULL
            ,SE_ANNO_CAD_DATA VARCHAR NULL
            ,LATITUDE VARCHAR NULL
            ,LONGITUDE VARCHAR NULL
            ,ACTIVE_RES_UNIT_COUNT VARCHAR NULL
            ,RES_TYPE VARCHAR NULL
            ,ACTIVE_RES_OCCUPANCY_COUNT VARCHAR NULL
            ,WARD_2002 VARCHAR NULL
            ,WARD_2012 VARCHAR NULL
            ,ANC_2002 VARCHAR NULL
            ,ANC_2012 VARCHAR NULL
            ,SMD_2002 VARCHAR NULL
            ,SMD_2012 VARCHAR NULL
            ,geometry    geometry
"""
,'census_blocks':"""
        OBJECTID VARCHAR NULL
        ,BLKGRP VARCHAR NULL
        ,BLOCK VARCHAR NULL
        ,GEOID VARCHAR NULL
        ,GEOID10 VARCHAR NULL
        ,ALAND10 VARCHAR NULL
        ,AWATER10 VARCHAR NULL
        ,P0010001 VARCHAR NULL
        ,P0010002 VARCHAR NULL
        ,P0010003 VARCHAR NULL
        ,P0010004 VARCHAR NULL
        ,P0010005 VARCHAR NULL
        ,P0010006 VARCHAR NULL
        ,P0010007 VARCHAR NULL
        ,P0010008 VARCHAR NULL
        ,OP000001 VARCHAR NULL
        ,OP000002 VARCHAR NULL
        ,OP000003 VARCHAR NULL
        ,OP000004 VARCHAR NULL
        ,P0020002 VARCHAR NULL
        ,P0020005 VARCHAR NULL
        ,P0020006 VARCHAR NULL
        ,P0020007 VARCHAR NULL
        ,P0020008 VARCHAR NULL
        ,P0020009 VARCHAR NULL
        ,P0020010 VARCHAR NULL
        ,OP00005 VARCHAR NULL
        ,OP00006 VARCHAR NULL
        ,OP00007 VARCHAR NULL
        ,OP00008 VARCHAR NULL
        ,P0030001 VARCHAR NULL
        ,P0030003 VARCHAR NULL
        ,P0030004 VARCHAR NULL
        ,P0030005 VARCHAR NULL
        ,P0030006 VARCHAR NULL
        ,P0030007 VARCHAR NULL
        ,P0030008 VARCHAR NULL
        ,OP00009 VARCHAR NULL
        ,OP00010 VARCHAR NULL
        ,OP00011 VARCHAR NULL
        ,OP00012 VARCHAR NULL
        ,P0040002 VARCHAR NULL
        ,P0040005 VARCHAR NULL
        ,P0040006 VARCHAR NULL
        ,P0040007 VARCHAR NULL
        ,P0040008 VARCHAR NULL
        ,P0040009 VARCHAR NULL
        ,P0040010 VARCHAR NULL
        ,OP000013 VARCHAR NULL
        ,OP000014 VARCHAR NULL
        ,OP000015 VARCHAR NULL
        ,OP000016 VARCHAR NULL
        ,H0010001 VARCHAR NULL
        ,H0010002 VARCHAR NULL
        ,H0010003 VARCHAR NULL
        ,ACRES VARCHAR NULL
        ,Shape_Length VARCHAR NULL
        ,Shape_Area VARCHAR NULL
        ,SQMILES VARCHAR NULL
        ,geometry geometry
"""
,'crash_details':"""
    OBJECTID VARCHAR NULL
    ,CRIMEID VARCHAR NULL
    ,CCN VARCHAR NULL
    ,PERSONID VARCHAR NULL
    ,PERSONTYPE VARCHAR NULL
    ,AGE VARCHAR NULL
    ,FATAL VARCHAR NULL
    ,MAJORINJURY VARCHAR NULL
    ,MINORINJURY VARCHAR NULL
    ,VEHICLEID VARCHAR NULL
    ,INVEHICLETYPE VARCHAR NULL
    ,TICKETISSUED VARCHAR NULL
    ,LICENSEPLATESTATE VARCHAR NULL
    ,IMPAIRED VARCHAR NULL
    ,SPEEDING VARCHAR NULL
    ,geometry geometry

"""
    }
    return data_model_dict[target_table]
