drop table if exists source_data.dcfems_unit_numbers_lookup;
create table source_data.dcfems_unit_numbers_lookup(
unit_number varchar null
	,unit_number_audio varchar[] null
)

insert into source_data.dcfems_unit_numbers_lookup
values 
('A01', ARRAY['ambulance one', 'ambulance 01', 'animals one', 'animals 01', 'animals 1 ', 'ambulance 1 ']),
('A03', ARRAY['ambulance three', 'ambulance 03', 'animals three', 'animals 03', 'animals 3 ', 'ambulance 3 ']),
('A04', ARRAY['ambulance four', 'ambulance 04','animals four', 'animals 04', 'animals 4', 'ambulance 4']),
('A06', ARRAY['ambulance six', 'ambulance 06','animals six', 'animals 06', 'animals 6', 'ambulance 6']),
('A08', ARRAY['ambulance eight', 'ambulance 08', 'ambulance aid', 'almost aid','animals eight', 'animals 08', 'animals aid', 'ambulance 8', 'animals 8']),
('A09', ARRAY['ambulance nine', 'ambulance 09','animals nine', 'animals 09', 'animals 9', 'ambulance 9']),
('A11', ARRAY['ambulance 11','animals 11']),
('A12', ARRAY['ambulance 12','animals 12']),
('A13', ARRAY['ambulance 13','animals 13']),
('A14', ARRAY['ambulance 14','animals 14']),
('A15', ARRAY['ambulance 15','animals 15']),
('A16', ARRAY['ambulance 16','animals 16']),
('A18', ARRAY['ambulance 18','animals 18']),
('A19', ARRAY['ambulance 19','animals 19']),
('A19B', ARRAY['ambulance 19 bravo', '19 bravo','animals 19 bravo']),
('A20', ARRAY['ambulance 20','animals 20']),
('A22', ARRAY['ambulance 22','animals 22']),
('A23', ARRAY['ambulance 23','animals 23']),
('A26', ARRAY['ambulance 26','animals 26']),
('A27', ARRAY['ambulance 27','animals 27']),
('A28', ARRAY['ambulance 28','animals 28']),
('A29', ARRAY['ambulance 29','animals 29']),
('A30', ARRAY['ambulance 30','animals 30']),
('A30B', ARRAY['ambulance 30 bravo', '30 bravo','animals 30 bravo']),
('A32', ARRAY['ambulance 32','animals 32']),
('A33', ARRAY['ambulance 33','animals 33']),
('A61', ARRAY['ambulance 61','animals 61']),
('A62', ARRAY['ambulance 62','animals 62']),
('A63', ARRAY['ambulance 63','animals 63']),
('A64', ARRAY['ambulance 64','animals 64']),
('A66', ARRAY['ambulance 66','animals 66']),
('BC1', ARRAY['battalion chief one', 'battalion one', 'italian one', 'italian 1']),
('BC2', ARRAY['battalion chief two', 'battalion two' ,'italian two', 'italian 2']),
('BC3', ARRAY['battalion chief three', 'battalion three', 'italian three', 'italian 3']),
('BC4', ARRAY['battalion chief four','battalion four', 'italian four', 'italian 4']),
('BC5', ARRAY['battalion chief five','battalion five', 'italian five', 'italian 5']),
('BC6', ARRAY['battalion chief six','battalion six', 'italian six', 'italian 6']),
('E01', ARRAY['engine one', 'engine 01','agent one', 'agent 01','medication one', 'medication 01', 'engine 1 ', 'agent 1 ', 'medication 1 ']),
('E02', ARRAY['engine two', 'engine 02','agent two', 'agent 02','medication two', 'medication 02', 'engine 2 ', 'agent 2 ', 'medication 2 ', 'engine to ']),
('E03', ARRAY['engine three', 'engine 03', 'agent three', 'agent 03', 'medication three', 'medication 03', 'engine 3 ', 'agent 3 ', 'medication 3 ']),
('E04', ARRAY['engine four', 'engine 04', 'agent four', 'agent 04', 'medication four', 'medication 04', 'engine 4', 'agent 4', 'medication 4']),
('E05', ARRAY['engine five', 'engine 05','agent five', 'agent 05','medication five', 'medication 05', 'engine 5', 'agent 5', 'medication 5']),
('E06', ARRAY['engine six', 'engine 06', 'agent six', 'agent 06', 'engines six', 'agents six', 'medication 06', 'medications six', 'engine 6', 'agent 6', 'medication 6']),
('E07', ARRAY['engine seven', 'engine 07', 'agent seven', 'agent 07', 'agents seven', 'engines seven', 'medication seven', 'medications seven', 'engine 7', 'agent 7', 'medication 7']),
('E08', ARRAY['engine eight', 'engine 08', 'engine aid', 'agent eight', 'agent 08', 'agent aid', 'medication eight', 'medication 08', 'medication aid', 'engine 8', 'agent 8', 'medication 8']),
('E09', ARRAY['engine nine', 'engine 09', 'agent nine', 'agent 09', 'medication nine', 'medication 09', 'engine 9', 'agent 9', 'medication 9']),
('E10', ARRAY['engine 10', 'agent 10', 'medication 10']),
('E11', ARRAY['engine 11', 'agent 11', 'medication 11']),
('E12', ARRAY['engine 12', 'agent 12', 'medication 12']),
('E13', ARRAY['engine 13', 'agent 13', 'medication 13']),
('E14', ARRAY['engine 14', 'agent 14', 'medication 14']),
('E15', ARRAY['engine 15', 'agent 15', 'medication 15']),
('E16', ARRAY['engine 16', 'engines 16', 'agent 16', 'agents 16', 'medication 16', 'medications 16']),
('E17', ARRAY['engine 17', 'engines 17', 'agent 17', 'agents 17', 'medication 17', 'medications 17']),
('E18', ARRAY['engine 18', 'agent 18', 'medication 18']),
('E19', ARRAY['engine 19', 'agent 19', 'medication 19']),
('E20', ARRAY['engine 20', 'agent 20', 'medication 20']),
('E21', ARRAY['engine 21', 'agent 21', 'medication 21']),
('E22', ARRAY['engine 22', 'agent 22', 'medication 22']),
('E23', ARRAY['engine 23', 'agent 23', 'medication 23']),
('E24', ARRAY['engine 24', 'agent 24', 'medication 24']),
('E25', ARRAY['engine 25', 'agent 25', 'medication 25']),
('E26', ARRAY['engine 26', 'agent 26', 'medication 26']),
('E27', ARRAY['engine 27', 'agent 27', 'medication 27']),
('E28', ARRAY['engine 28', 'agent 28', 'medication 28']),
('E29', ARRAY['engine 29', 'agent 29', 'medication 29']),
('E30', ARRAY['engine 30', 'agent 30', 'medication 30']),
('E31', ARRAY['engine 31', 'agent 31', 'medication 31']),
('E32', ARRAY['engine 32', 'agent 32', 'medication 32']),
('E33', ARRAY['engine 33', 'agent 33', 'medication 33']),
('E52', ARRAY['engine 52', 'agent 52', 'medication 52']),
('E53', ARRAY['engine 53', 'agent 53', 'medication 53']),
('E63', ARRAY['engine 63', 'engines 63', 'engines 63']),
('E71', ARRAY['engine 71', 'engines 71', 'engines 71']),
('M01', ARRAY['medic one', 'medic 01']),
('M02', ARRAY['medic two', 'medic 02', 'medic to ']),
('M03', ARRAY['medic three', 'medic 03', 'medic 3 ']),
('M05', ARRAY['medic five', 'medic 05', 'medic 5']),
('M07', ARRAY['medic seven', 'medic 07', 'medic 7']),
('M08', ARRAY['medic eight', 'medic 08', 'medic aid', 'medicaid']),
('M10', ARRAY['medic 10']),
('M14', ARRAY['medic 14']),
('M17', ARRAY['medic 17', 'medics 17']),
('M19', ARRAY['medic 19']),
('M21', ARRAY['medic 21']),
('M24', ARRAY['medic 24']),
('M25', ARRAY['medic 25']),
('M27', ARRAY['medic 27']),
('M30', ARRAY['medic 30']),
('M31', ARRAY['medic 31']),
('M33', ARRAY['medic 33']),
('R1', ARRAY['rescue one', 'squad one','rescue 1', 'squad 1']),
('R2', ARRAY['rescue two', 'squad two','rescue 2', 'squad 2 ', 'rescue squad to ']),
('R3', ARRAY['rescue three', 'squad three','rescue 3', 'squad 3 ']),
('T02', ARRAY[' truck two', 'truck 02', ' truck 2', ' truck to ']),
('T03', ARRAY[' truck three', 'truck 03', ' truck 3']),
('T04', ARRAY[' truck four', 'truck 04', ' truck 4']),
('T05', ARRAY[' truck five', 'truck 05', ' truck 5']),
('T06', ARRAY[' truck six', 'truck 06', ' trucks six', ' truck 6 ']),
('T07', ARRAY[' truck seven', 'truck 07', ' trucks seven', ' truck 7']),
('T08', ARRAY[' truck eight', 'truck 08', ' truck aid', ' truck 8']),
('T09', ARRAY[' truck nine', 'truck 09', ' truck 9']),
('T10', ARRAY[' truck 10']),
('T11', ARRAY[' truck 11']),
('T12', ARRAY[' truck 12']),
('T13', ARRAY[' truck 13']),
('T14', ARRAY[' truck 14']),
('T15', ARRAY[' truck 15']),
('T16', ARRAY[' truck 16', ' trucks 16']),
('T17', ARRAY[' truck 17', ' trucks 17']),
('TW3', ARRAY['tower three', 'tower 03'])


